---
title: "R Notebook"
output: html_notebook
---

```{r}
set.seed(1234)
library (tm)
importdf = read.csv('dfnlp.csv', header = F, stringsAsFactors = F)
```

```{r}
import_corpus = Corpus(VectorSource(importdf))
```
```{r}
tdm = TermDocumentMatrix(import_corpus,
                         control = list(weighting = weightTfIdf,
                          stemming = TRUE, #create root words
                          stopwords = TRUE, #remove stop words
                          minWordLength = 3, #cut out small words
                          removeNumbers = TRUE, #take out the numbers
                          removePunctuation = TRUE)) #take out
```

```{r}
library (cluster)
set.seed(1234)
m <- as.matrix(tdm)
#compute distance between document vectors
d <- dist(m)
#kmeans clustering
#kmeans - run with nstart=100 and k=2,3,5 
kfit <- kmeans(d, 2, nstart=100)
#plot - 
clusplot(as.matrix(d), kfit$cluster, color=T, shade=T, labels=2, lines=0)

```

```{r}
wss <- 2:(length(tdm)-1)
for (i in 2:(length(tdm)-1)) wss[i] <- sum(kmeans(d,centers=i,nstart=25)$withinss)
plot(2:(length(tdm)-1), wss[2:(length(tdm)-1)], type="b", xlab="Number of Clusters",
     ylab="Within groups sum of squares") 
```
```{r}
m <- as.matrix(tdm)
#compute distance between document vectors
d <- dist(m)
#kmeans clustering
#kmeans - run with nstart=100 and k=2,3,5 
kfit <- kmeans(d, 3, nstart=100)
#plot - 
clusplot(as.matrix(d), kfit$cluster, color=T, shade=T, labels=2, lines=0)
```
```{r}
km.res<-kmeans(d,3, nstart=100)
print(km.res)
```
```{r}
library(factoextra)
```

```{r}
fviz_cluster(km.res, m)
```

